apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-frontend
      version: base
  template:
    metadata:
      labels:
        app: todo-app-frontend
        version: base
    spec:
      containers:
      - name: todo-app-frontend
        image: fsteccanella/todo-app-frontend
        imagePullPolicy: Always
        env:
          - name: TODO_API_SERVER
            value: todo-app-backend:3000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
